import os, re

blog_dir = r"C:\Users\user\.openclaw\workspace\gold-web-v2\my-gold-price\app\blog"
base_url = "https://www.gold-tw.com"

# 主題群組：每篇文章定義 3-4 個最相關的內部連結
internal_links = {
    "gold-appraise": [
        ("/blog/gold-recycling-process", "黃金回收流程完整說明"),
        ("/blog/what-to-bring-when-selling-gold-2026", "賣黃金要帶什麼？完整清單"),
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
    ],
    "gold-recycling-process": [
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
        ("/blog/gold-id-requirement", "賣黃金需要帶什麼證件？"),
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
    ],
    "gold-scam-prevent": [
        ("/blog/gold-scale-trap", "黃金秤重陷阱揭露"),
        ("/blog/gold-recovery-traps", "黃金回收常見陷阱"),
        ("/blog/how-to-choose-gold-shop", "如何選擇可信賴的黃金回收店"),
        ("/blog/gold-safety", "黃金交易安全指南"),
    ],
    "gold-scale-trap": [
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
        ("/blog/gold-recovery-traps", "黃金回收常見陷阱"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/how-to-choose-gold-shop", "如何選擇可信賴的黃金回收店"),
    ],
    "gold-recovery-traps": [
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
        ("/blog/gold-scale-trap", "黃金秤重陷阱揭露"),
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
    ],
    "gold-9999-recovery": [
        ("/blog/karat-gold-recovery", "K金回收完整指南"),
        ("/blog/gold-purity", "黃金純度完整說明"),
        ("/blog/gold-bar-recovery", "黃金條塊回收指南"),
        ("/blog/gold-vs-k-gold-vs-platinum", "黃金 vs K金 vs 白金比較"),
    ],
    "karat-gold-recovery": [
        ("/blog/gold-9999-recovery", "9999純金回收高價收購"),
        ("/blog/karat-gold-guide", "K金完整指南"),
        ("/blog/gold-purity", "黃金純度完整說明"),
        ("/blog/gold-identification", "黃金鑑定方法"),
    ],
    "karat-gold-guide": [
        ("/blog/karat-gold-recovery", "K金回收完整指南"),
        ("/blog/gold-purity", "黃金純度完整說明"),
        ("/blog/gold-identification", "黃金鑑定方法"),
        ("/blog/gold-vs-k-gold-vs-platinum", "黃金 vs K金 vs 白金比較"),
    ],
    "gold-purity": [
        ("/blog/gold-identification", "黃金鑑定方法"),
        ("/blog/karat-gold-guide", "K金完整指南"),
        ("/blog/gold-9999-recovery", "9999純金回收高價收購"),
        ("/blog/gold-vs-k-gold-vs-platinum", "黃金 vs K金 vs 白金比較"),
    ],
    "gold-identification": [
        ("/blog/gold-purity", "黃金純度完整說明"),
        ("/blog/karat-gold-guide", "K金完整指南"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
    ],
    "gold-ring-recovery": [
        ("/blog/gold-necklace-recovery", "黃金項鍊回收指南"),
        ("/blog/gold-bracelet-recovery", "黃金手鍊回收指南"),
        ("/blog/karat-gold-recovery", "K金回收完整指南"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "gold-necklace-recovery": [
        ("/blog/gold-ring-recovery", "黃金戒指回收指南"),
        ("/blog/gold-bracelet-recovery", "黃金手鍊回收指南"),
        ("/blog/gold-pendant-recovery", "黃金吊墜回收指南"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "gold-bracelet-recovery": [
        ("/blog/gold-necklace-recovery", "黃金項鍊回收指南"),
        ("/blog/gold-ring-recovery", "黃金戒指回收指南"),
        ("/blog/karat-gold-recovery", "K金回收完整指南"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "gold-earring-recovery": [
        ("/blog/gold-ring-recovery", "黃金戒指回收指南"),
        ("/blog/gold-necklace-recovery", "黃金項鍊回收指南"),
        ("/blog/diamond-jewelry", "鑽石珠寶收購｜GIA鑽石估價"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "gold-pendant-recovery": [
        ("/blog/gold-necklace-recovery", "黃金項鍊回收指南"),
        ("/blog/gold-ring-recovery", "黃金戒指回收指南"),
        ("/blog/diamond-jewelry", "鑽石珠寶收購｜GIA鑽石估價"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "gold-watch-recovery": [
        ("/blog/diamond-jewelry", "鑽石珠寶收購｜GIA鑽石估價"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
        ("/blog/how-to-choose-gold-shop", "如何選擇可信賴的黃金回收店"),
    ],
    "diamond-jewelry": [
        ("/blog/gold-earring-recovery", "黃金耳環回收指南"),
        ("/blog/gold-ring-recovery", "黃金戒指回收指南"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
    ],
    "gold-bar-recovery": [
        ("/blog/gold-9999-recovery", "9999純金回收高價收購"),
        ("/blog/gold-coin-invest", "黃金硬幣投資指南"),
        ("/blog/gold-purity", "黃金純度完整說明"),
        ("/blog/gold-liquid", "黃金變現完整指南"),
    ],
    "gold-coin-invest": [
        ("/blog/gold-bar-recovery", "黃金條塊回收指南"),
        ("/blog/gold-9999-recovery", "9999純金回收高價收購"),
        ("/blog/gold-liquid", "黃金變現完整指南"),
        ("/blog/gold-coin-recovery", "金幣回收指南"),
    ],
    "gold-coin-recovery": [
        ("/blog/gold-coin-invest", "黃金硬幣投資指南"),
        ("/blog/gold-bar-recovery", "黃金條塊回收指南"),
        ("/blog/gold-9999-recovery", "9999純金回收高價收購"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "gold-liquid": [
        ("/blog/gold-auction", "黃金拍賣 vs 直接回收比較"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
    ],
    "gold-auction": [
        ("/blog/gold-liquid", "黃金變現完整指南"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
    ],
    "gold-price-2026": [
        ("/blog/gold-price-forecast-2026", "2026年黃金價格預測"),
        ("/blog/factors-affecting-gold-price", "影響黃金價格的因素"),
        ("/blog/gold-price-key-factors", "黃金價格關鍵因素"),
        ("/blog/gold-vs-platinum", "黃金 vs 白金投資比較"),
    ],
    "gold-price-forecast-2026": [
        ("/blog/gold-price-2026", "2026年黃金行情分析"),
        ("/blog/factors-affecting-gold-price", "影響黃金價格的因素"),
        ("/blog/gold-coin-invest", "黃金硬幣投資指南"),
        ("/blog/gold-vs-platinum-investment", "黃金 vs 白金投資比較"),
    ],
    "factors-affecting-gold-price": [
        ("/blog/gold-price-2026", "2026年黃金行情分析"),
        ("/blog/gold-price-forecast-2026", "2026年黃金價格預測"),
        ("/blog/gold-price-key-factors", "黃金價格關鍵因素"),
        ("/blog/gold-liquid", "黃金變現完整指南"),
    ],
    "gold-price-key-factors": [
        ("/blog/factors-affecting-gold-price", "影響黃金價格的因素"),
        ("/blog/gold-price-2026", "2026年黃金行情分析"),
        ("/blog/gold-recycling-price-factors", "黃金回收價格因素"),
        ("/blog/gold-liquid", "黃金變現完整指南"),
    ],
    "gold-recycling-price-factors": [
        ("/blog/factors-affecting-gold-price", "影響黃金價格的因素"),
        ("/blog/gold-price-key-factors", "黃金價格關鍵因素"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/gold-shop-vs-recycling-shop", "銀樓 vs 回收商比較"),
    ],
    "gold-shop-recommend": [
        ("/blog/how-to-choose-gold-shop", "如何選擇可信賴的黃金回收店"),
        ("/blog/gold-shop-vs-recycling-shop", "銀樓 vs 回收商比較"),
        ("/blog/taipei-gold-recovery", "台北黃金回收推薦"),
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
    ],
    "how-to-choose-gold-shop": [
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
        ("/blog/gold-shop-vs-recycling-shop", "銀樓 vs 回收商比較"),
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
        ("/blog/gold-safety", "黃金交易安全指南"),
    ],
    "gold-shop-vs-recycling-shop": [
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
        ("/blog/how-to-choose-gold-shop", "如何選擇可信賴的黃金回收店"),
        ("/blog/gold-shop-vs-silver-shop", "黃金回收商 vs 銀樓比較"),
        ("/blog/gold-auction", "黃金拍賣 vs 直接回收比較"),
    ],
    "gold-shop-vs-silver-shop": [
        ("/blog/gold-shop-vs-recycling-shop", "銀樓 vs 回收商比較"),
        ("/blog/how-to-choose-gold-shop", "如何選擇可信賴的黃金回收店"),
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "wedding-gold-recovery": [
        ("/blog/gold-jewelry-recovery", "黃金首飾回收指南"),
        ("/blog/inheritance-gold", "繼承黃金處理指南"),
        ("/blog/gold-family", "家傳黃金變現指南"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "inheritance-gold": [
        ("/blog/wedding-gold-recovery", "嫁妝黃金回收指南"),
        ("/blog/gold-family", "家傳黃金變現指南"),
        ("/blog/gold-antique", "古早黃金回收指南"),
        ("/blog/gold-tax", "黃金回收稅務說明"),
    ],
    "gold-family": [
        ("/blog/inheritance-gold", "繼承黃金處理指南"),
        ("/blog/wedding-gold-recovery", "嫁妝黃金回收指南"),
        ("/blog/gold-antique", "古早黃金回收指南"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "gold-antique": [
        ("/blog/inheritance-gold", "繼承黃金處理指南"),
        ("/blog/gold-family", "家傳黃金變現指南"),
        ("/blog/old-gold-recovery", "舊金回收完整指南"),
        ("/blog/gold-purity", "黃金純度完整說明"),
    ],
    "gold-birthday-gift": [
        ("/blog/gold-jewelry-recovery", "黃金首飾回收指南"),
        ("/blog/gold-ring-recovery", "黃金戒指回收指南"),
        ("/blog/gold-necklace-recovery", "黃金項鍊回收指南"),
        ("/blog/gold-tradition", "黃金傳統文化說明"),
    ],
    "gold-tradition": [
        ("/blog/gold-birthday-gift", "黃金生日禮物推薦"),
        ("/blog/gold-culture", "黃金文化歷史"),
        ("/blog/gold-family", "家傳黃金變現指南"),
        ("/blog/gold-weight", "黃金重量單位換算"),
    ],
    "gold-culture": [
        ("/blog/gold-tradition", "黃金傳統文化說明"),
        ("/blog/gold-weight", "黃金重量單位換算"),
        ("/blog/gold-purity", "黃金純度完整說明"),
        ("/blog/lion-head-gold", "獅頭金飾回收指南"),
    ],
    "lion-head-gold": [
        ("/blog/gold-culture", "黃金文化歷史"),
        ("/blog/gold-tradition", "黃金傳統文化說明"),
        ("/blog/gold-antique", "古早黃金回收指南"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "gold-weight": [
        ("/blog/gold-purity", "黃金純度完整說明"),
        ("/blog/gold-calculator", "黃金回收計算器"),
        ("/blog/karat-gold-guide", "K金完整指南"),
        ("/blog/gold-culture", "黃金文化歷史"),
    ],
    "gold-calculator": [
        ("/blog/gold-weight", "黃金重量單位換算"),
        ("/blog/gold-purity", "黃金純度完整說明"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/today-gold-price" if False else "/blog/gold-price-2026", "2026年黃金行情分析"),
    ],
    "gold-insurance": [
        ("/blog/gold-safety", "黃金交易安全指南"),
        ("/blog/gold-liquid", "黃金變現完整指南"),
        ("/blog/gold-coin-invest", "黃金硬幣投資指南"),
        ("/blog/gold-bar-recovery", "黃金條塊回收指南"),
    ],
    "gold-safety": [
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
        ("/blog/gold-insurance", "黃金保險說明"),
        ("/blog/gold-recovery-traps", "黃金回收常見陷阱"),
        ("/blog/how-to-choose-gold-shop", "如何選擇可信賴的黃金回收店"),
    ],
    "gold-tax": [
        ("/blog/inheritance-gold", "繼承黃金處理指南"),
        ("/blog/gold-liquid", "黃金變現完整指南"),
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
        ("/blog/gold-should-know", "賣黃金必知事項"),
    ],
    "gold-should-know": [
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/gold-id-requirement", "賣黃金需要帶什麼證件？"),
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
    ],
    "before-selling-gold": [
        ("/blog/gold-should-know", "賣黃金必知事項"),
        ("/blog/gold-id-requirement", "賣黃金需要帶什麼證件？"),
        ("/blog/what-to-bring-when-selling-gold-2026", "賣黃金要帶什麼？完整清單"),
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
    ],
    "gold-id-requirement": [
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
        ("/blog/what-to-bring-when-selling-gold-2026", "賣黃金要帶什麼？完整清單"),
        ("/blog/gold-should-know", "賣黃金必知事項"),
        ("/blog/gold-recycling-process", "黃金回收流程完整說明"),
    ],
    "what-to-bring-when-selling-gold-2026": [
        ("/blog/gold-id-requirement", "賣黃金需要帶什麼證件？"),
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
        ("/blog/gold-should-know", "賣黃金必知事項"),
        ("/blog/gold-recycling-process", "黃金回收流程完整說明"),
    ],
    "sell-gold-tips": [
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
        ("/blog/why-some-get-better-gold-price", "為什麼有人能拿到更高的黃金回收價？"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "why-some-get-better-gold-price": [
        ("/blog/sell-gold-tips", "賣黃金技巧大全"),
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "gold-recovery-faq": [
        ("/blog/gold-recovery-faq-2026", "2026年黃金回收常見問題"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/gold-recycling-process", "黃金回收流程完整說明"),
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
    ],
    "gold-recovery-faq-2026": [
        ("/blog/gold-recovery-faq", "黃金回收常見問題"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/gold-recycling-process", "黃金回收流程完整說明"),
        ("/blog/what-to-bring-when-selling-gold-2026", "賣黃金要帶什麼？完整清單"),
    ],
    "gold-recycling-precautions": [
        ("/blog/gold-scam-prevent", "黃金回收詐騙防範指南"),
        ("/blog/gold-recovery-traps", "黃金回收常見陷阱"),
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
        ("/blog/how-to-choose-gold-shop", "如何選擇可信賴的黃金回收店"),
    ],
    "gold-recycling-tips": [
        ("/blog/sell-gold-tips", "賣黃金技巧大全"),
        ("/blog/why-some-get-better-gold-price", "為什麼有人能拿到更高的黃金回收價？"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/gold-shop-recommend", "台北黃金回收店推薦"),
    ],
    "gold-recycling-process": [
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/gold-id-requirement", "賣黃金需要帶什麼證件？"),
        ("/blog/before-selling-gold", "賣黃金前必做的準備"),
        ("/blog/gold-recovery-faq", "黃金回收常見問題"),
    ],
    "gold-jewelry-recovery": [
        ("/blog/gold-ring-recovery", "黃金戒指回收指南"),
        ("/blog/gold-necklace-recovery", "黃金項鍊回收指南"),
        ("/blog/diamond-jewelry", "鑽石珠寶收購｜GIA鑽石估價"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "old-gold-recovery": [
        ("/blog/gold-antique", "古早黃金回收指南"),
        ("/blog/broken-gold-recovery", "斷裂黃金回收指南"),
        ("/blog/inheritance-gold", "繼承黃金處理指南"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
    ],
    "broken-gold-recovery": [
        ("/blog/old-gold-recovery", "舊金回收完整指南"),
        ("/blog/gold-jewelry-recovery", "黃金首飾回收指南"),
        ("/blog/gold-appraise", "黃金估價｜免費專業鑑定"),
        ("/blog/gold-recycling-process", "黃金回收流程完整說明"),
    ],
    "gold-vs-platinum": [
        ("/blog/gold-vs-k-gold-vs-platinum", "黃金 vs K金 vs 白金比較"),
        ("/blog/platinum-recovery", "白金回收完整指南"),
        ("/blog/gold-vs-platinum-investment", "黃金 vs 白金投資比較"),
        ("/blog/gold-price-2026", "2026年黃金行情分析"),
    ],
    "gold-vs-k-gold-vs-platinum": [
        ("/blog/